// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzENSquAl9Yso5UcP8a-HBUceGrG7cVpw',
    appId: '1:329126827394:web:5e29d5f42ef000a8cdab9b',
    messagingSenderId: '329126827394',
    projectId: 'oxywatch-d9ff0',
    authDomain: 'oxywatch-d9ff0.firebaseapp.com',
    storageBucket: 'oxywatch-d9ff0.firebasestorage.app',
    measurementId: 'G-8LQNQSFD70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFburCMXpUlwwkO__6WTIYP7NEs1RF4ds',
    appId: '1:329126827394:android:8193443998586208cdab9b',
    messagingSenderId: '329126827394',
    projectId: 'oxywatch-d9ff0',
    storageBucket: 'oxywatch-d9ff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB5HIREyEEPVbw3RybckE8HuHkxpcfiFc',
    appId: '1:329126827394:ios:187d2819040bb618cdab9b',
    messagingSenderId: '329126827394',
    projectId: 'oxywatch-d9ff0',
    storageBucket: 'oxywatch-d9ff0.firebasestorage.app',
    iosBundleId: 'com.example.oxywatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB5HIREyEEPVbw3RybckE8HuHkxpcfiFc',
    appId: '1:329126827394:ios:187d2819040bb618cdab9b',
    messagingSenderId: '329126827394',
    projectId: 'oxywatch-d9ff0',
    storageBucket: 'oxywatch-d9ff0.firebasestorage.app',
    iosBundleId: 'com.example.oxywatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzENSquAl9Yso5UcP8a-HBUceGrG7cVpw',
    appId: '1:329126827394:web:4f4c9f71a585ab0ccdab9b',
    messagingSenderId: '329126827394',
    projectId: 'oxywatch-d9ff0',
    authDomain: 'oxywatch-d9ff0.firebaseapp.com',
    storageBucket: 'oxywatch-d9ff0.firebasestorage.app',
    measurementId: 'G-405D2KS1RL',
  );
}
